baseURL = "https://isac-8oxfp.ondigitalocean.app/"
#baseURL = "http://localhost/optica/"
languageCode = "en-us"
title = "ISAC"
theme = "opticaTheme"

############################# Plugins ##############################
[params.plugins]
  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"  
  [[params.plugins.css]]
  URL = "fonts/font-awesome/css/font-awesome.min.css" 

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/jQuery/custom.js"  

#################### navigation ################################
[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = ""
    weight = 1
  [[menu.main]]
    name = "Products"
    pre = "pen-tool"
    url = "products"
    weight = 2
  [[menu.main]]
    name = "Services"
    pre = "tag"
    url = "services"
    weight = 3
  [[menu.main]]
    name = "Resources"
    pre = "tag"
    url = "resources"
    weight = 4
  [[menu.main]]
    name = "Partnerships"
    pre = "tag"
    url = "partnerships"
    weight = 5
  [[menu.main]]
    name = "Company"
    pre = "tag"
    url = "company"
    weight = 6


#################### default parameters ################################
[params]
logo = "images/optica-logo2-2021.png"
home = "Home"
# Meta data
description = "This is meta description"
author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "" # Your ID
# copyright
copyright = "Copyright &copy; 2020 [Resecure](https://resecure.com.au) All Rights Reserved"
# Navigation get start button
[params.navButton]
enable = true

# do_not_log_list : add configurations that you do not wish to be recorded in logs
#do_not_log_list = "['send_grid_secret_key']"
